---
# tasks file for ansible-role-docker-airflow

- include: prometheus.yml
  when: install_docker

#- include: prometheus.yml
#  when: prometheus_enable

- include: ssl.yml
  when: ssl_enable

- include: airflow.yml
