route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        text: "{{ .CommonAnnotations.description }}"
        username: 'Prometheus'
        channel: '#{{ alertmanager_slack_channel }}'
        api_url: 'https://hooks.slack.com/services/{{ alertmanager_slack_api_key }}'
