version: '2.1'

x-disabled-service:
  &disabled-service
  image: tianon/true
  restart: "no"
  command: ""
  entrypoint: ""

networks:
  monitor-net:
    driver: bridge

volumes:
  dag_data: {}
  postgres_data: {}
  prometheus_data: {}
  grafana_data: {}

services:
  redis:
    <<: *disabled-service
  
  postgres:
    <<: *disabled-service
  
  webserver:
    <<: *disabled-service
  
  flower:
    <<: *disabled-service
  
  scheduler:
    <<: *disabled-service
  
  worker:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    environment:
      - EXECUTOR=Celery
      - FERNET_KEY=${FERNET_KEY:-46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=}
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass}
    command: worker
    
  prometheus:
    <<: *disabled-service
  
  alertmanager:
    <<: *disabled-service
  
  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  
  cadvisor:
    <<: *disabled-service
  
  grafana:
    <<: *disabled-service
  
  pushgateway:
    <<: *disabled-service
  
  caddy:
    <<: *disabled-service
